/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NewRouteImport } from './routes/new'
import { Route as LocksRouteImport } from './routes/locks'
import { Route as InitRouteImport } from './routes/init'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LocksRoute = LocksRouteImport.update({
  id: '/locks',
  path: '/locks',
  getParentRoute: () => rootRouteImport,
} as any)
const InitRoute = InitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/init': typeof InitRoute
  '/locks': typeof LocksRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/init': typeof InitRoute
  '/locks': typeof LocksRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/init': typeof InitRoute
  '/locks': typeof LocksRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/init' | '/locks' | '/new' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/init' | '/locks' | '/new' | '/settings'
  id: '__root__' | '/' | '/init' | '/locks' | '/new' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InitRoute: typeof InitRoute
  LocksRoute: typeof LocksRoute
  NewRoute: typeof NewRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locks': {
      id: '/locks'
      path: '/locks'
      fullPath: '/locks'
      preLoaderRoute: typeof LocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/init': {
      id: '/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof InitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InitRoute: InitRoute,
  LocksRoute: LocksRoute,
  NewRoute: NewRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
